### ISSUE TITLE
Error: Cannot find module '@payloadcms/plugin-relationship-object-ids'

### ISSUE THREAD

**Issue by zazz-ops** [payloadcms/plugin-relationship-object-ids#4]
I'm attempting to install this plugin and I'm getting a fireworks of errors.

First, when I follow the instructions in the README that say "just import and install it" I get the following error:
`Error: Cannot find module '@payloadcms/plugin-relationship-object-ids'`

So I thought maybe I needed to install it from npm, so I run `npm install --save @payloadcms/plugin-relationship-object-ids` and I get the following error:

<img width="787" alt="image" src="https://github.com/payloadcms/plugin-relationship-object-ids/assets/151117554/b9ef5994-5693-4b54-a1a7-add11b6547ea">

Does this plugin work with Payload 2.8.1? If so, how do I go about utilizing it without error?

**Comment by zazz-ops** [comment]
@jmikrut Any advice on how I should go about getting this plugin to install properly via npm?

**Comment by olivier5741** [comment]
Hi there, I'm running through the same issue. I suppose the plugin payloadCMS version needs to be upgraded from 1.9.5 to 2.x.x :). I have no idea about the impact, it looks like a beforeChange hook assigned to every relationship field.

**Comment by olivier5741** [comment]
I created a draft pull request for the issue :) : https://github.com/payloadcms/plugin-relationship-object-ids/pull/5

**Comment by Rikhart** [comment]
Hi @olivier5741  i am facingt the same issue, now i am using payload 2.12.1 also i has been tested your fork but always save as a String the relationship fields.

I am importing and using as the docs says

![Captura de pantalla 2024-04-11 a la(s) 11 37 39 p  m](https://github.com/payloadcms/plugin-relationship-object-ids/assets/1900153/3b9be838-5f05-4758-a1cb-b11823d6ed20)

Exist something that i missing in the configuration or something aditiontal in the collection setup to get that my fields save as a Object Id?

Thanks for your help.

**Comment by olivier5741** [comment]
Hi @Rikhart, I forgot to commit a peer dependency that I just synced now but I don't know if it has an effect. Last time, I copy pasted the content of `/dist` into my project to use it and it seemed to work. I now abandonned this plugin, there were too many problems coming up. I just accepted relations (foreign key) to be a string and not an object id. Anyway, in one or two collection I had the ids being a "human comprehensive" string instead of an object id anyway :D

**Comment by olivier5741** [comment]
Some extra updates, so I'm using gatsbyjs on the same database, fairly easy to make it work with objectids as string. I'm also using **Mongo Charts but there it's a pain to do relationships when foreign keys are string, you need to convert formats ...**

**Comment by olivier5741** [comment]
I'm still looking for a work around to make payload happy and have the other tools happy as well. One idea is to keep Payload doing its stuff and add an extra field to hold the ObjectId. This only works if you update documents solely through Payload ...

```
    {
      name: 'place',
      type: 'relationship',
      relationTo: 'places',
      hasMany: false, 
    },
    {
      name: 'placeId',
      type: 'richText',
      hooks: {
        beforeChange: [({ siblingData}) => {
          if(!siblingData.place) return siblingData.place
          return new Types.ObjectId(siblingData.place)
        }]
      },
      admin: {
        hidden: true
      }
    },
`
``

**Comment by locvfx** [comment]
you need higher version
https://www.npmjs.com/package/@payloadcms/plugin-relationship-object-ids/v/3.0.0-beta.72

`npm i @payloadcms/plugin-relationship-object-ids@3.0.0-beta.72`

**Comment by locvfx** [comment]
> I'm attempting to install this plugin and I'm getting a fireworks of errors.
> 
> First, when I follow the instructions in the README that say "just import and install it" I get the following error: `Error: Cannot find module '@payloadcms/plugin-relationship-object-ids'`
> 
> So I thought maybe I needed to install it from npm, so I run `npm install --save @payloadcms/plugin-relationship-object-ids` and I get the following error:
> 
> <img alt="image" width="787" src="https://private-user-images.githubusercontent.com/151117554/300243725-b9ef5994-5693-4b54-a1a7-add11b6547ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDUwMjk0NTAsIm5iZiI6MTc0NTAyOTE1MCwicGF0aCI6Ii8xNTExMTc1NTQvMzAwMjQzNzI1LWI5ZWY1OTk0LTU2OTMtNGI1NC1hMWE3LWFkZDExYjY1NDdlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDQxOVQwMjE5MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZGUwODZhZjQxMDIyMGM5NTVmMzc5MTgzYmViNjc2NmQ1Nzk3Nzg3ZTE0YTMzNzI4MTFkNTI2YTYyNzhmYjFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.C6XTed5r-VOrUJxKgJhOC7hakaAa9H2HL8om57AwS-0">
> Does this plugin work with Payload 2.8.1? If so, how do I go about utilizing it without error?


you need higher version
https://www.npmjs.com/package/@payloadcms/plugin-relationship-object-ids/v/3.0.0-beta.72

`npm i @payloadcms/plugin-relationship-object-ids@3.0.0-beta.72`

**Comment by olivier5741** [comment]
Hi, I migrated to Payload 3 to solve the issue, it is saving relationships as objectIds natively 🙂. No need to get the plugin anymore. I don't know how polymorphic relationship ids are saved since I have none ...
